# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Natalia Go'
description: 'Storyteller.'

# Images
avatar: 'book_avatar.jpg'
background: 'book-bg.jpg'
favicon: 'favicon.ico'

# Online profiles
# facebook: ''
# twitter: ''
linkedin: ''
instagram: ''
pinterest: ''
youtube: ''
github-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
# weibo: ''
# vk: ''
# blog_url: ''
email: ''
# messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
